import 'package:json_annotation/json_annotation.dart';
import 'package:med_track/database/model/entity.dart';
import 'package:uuid/uuid.dart';

part 'account_link.g.dart';

/// A caregiver/family relationship between two MedTrack accounts.
///
/// Created when a caregiver scans the QR code generated by a patient (the
/// account owner). For now it only records the relationship; viewing the
/// patient's data through this link is intentionally out of scope.
///
/// Display fields (name/email) are denormalised so each side can render the
/// other account without a cross-account read.
@JsonSerializable()
class AccountLink implements IEntity {
  @override
  @JsonKey(includeFromJson: false, includeToJson: false)
  final String id;

  /// The account owner who generated the QR code (the shared account).
  final String patientUserId;
  final String patientName;
  final String patientEmail;

  /// The caregiver who scanned the QR code.
  final String caregiverUserId;
  final String caregiverName;
  final String caregiverEmail;

  final DateTime createdAt;

  AccountLink({
    String? id,
    required this.patientUserId,
    required this.patientName,
    required this.patientEmail,
    required this.caregiverUserId,
    required this.caregiverName,
    required this.caregiverEmail,
    DateTime? createdAt,
  })  : id = id ?? const Uuid().v4(),
        createdAt = createdAt ?? DateTime.now();

  /// Deterministic document id so Firestore security rules can verify a link
  /// via `exists()` without an extra query (see `firestore.rules`).
  static String buildId(String patientUserId, String caregiverUserId) =>
      '${patientUserId}_$caregiverUserId';

  factory AccountLink.fromJson(Map<String, dynamic> json, {String? id}) {
    final link = _$AccountLinkFromJson(json);
    return link.copyWith(id: id);
  }

  Map<String, dynamic> toJson() => _$AccountLinkToJson(this);

  AccountLink copyWith({
    String? id,
    String? patientUserId,
    String? patientName,
    String? patientEmail,
    String? caregiverUserId,
    String? caregiverName,
    String? caregiverEmail,
    DateTime? createdAt,
  }) {
    return AccountLink(
      id: id ?? this.id,
      patientUserId: patientUserId ?? this.patientUserId,
      patientName: patientName ?? this.patientName,
      patientEmail: patientEmail ?? this.patientEmail,
      caregiverUserId: caregiverUserId ?? this.caregiverUserId,
      caregiverName: caregiverName ?? this.caregiverName,
      caregiverEmail: caregiverEmail ?? this.caregiverEmail,
      createdAt: createdAt ?? this.createdAt,
    );
  }
}
